# Generated by Django 5.2.7 on 2025-10-14 23:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tiene_comision', models.BooleanField(default=False, help_text='Si este método de pago tiene comisión')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión aplicado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('genera_factura', models.BooleanField(default=True, help_text='Si este método de pago genera factura legal')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en las listas')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cajero_actual', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['cajero', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punto_venta_asignado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, help_text='Nombre del cliente si no es estudiante', max_length=150)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], default='pendiente', max_length=15)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cajero', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['cajero', 'administrador']}, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('hijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='usuarios.perfilhijo')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia, autorización, etc.', max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('tipo_factura', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura Exenta'), ('factura_afecta', 'Factura Afecta')], default='boleta', max_length=15)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_direccion', models.TextField(blank=True, null=True)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto_factura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_documento', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Factura/Boleta',
                'verbose_name_plural': 'Facturas/Boletas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Cantidad × Precio unitario', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_detalle', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
