# Generated by Django 5.2.7 on 2025-10-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilhijo_codigo_tarjeta_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='venta',
            name='hijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='usuarios.perfilhijo'),
        ),
    ]
