# Generated by Django 5.2.7 on 2025-10-12 05:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_estudiante_venta_hijo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Factura/Boleta', 'verbose_name_plural': 'Facturas/Boletas'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_ruc',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada'), ('vencida', 'Vencida')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='notas_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/pdf/'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto_factura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura Exenta'), ('factura_afecta', 'Factura Afecta')], default='boleta', max_length=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_documento', to='ventas.venta'),
        ),
    ]
