# Generated by Django 5.2.7 on 2025-10-14 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(default='La Cantina de Tita', max_length=200)),
                ('empresa_rut', models.CharField(default='76.123.456-7', max_length=20)),
                ('empresa_direccion', models.TextField(default='Av. Principal 123, Santiago, Chile')),
                ('empresa_telefono', models.CharField(default='+56 9 1234 5678', max_length=20)),
                ('empresa_email', models.EmailField(default='info@cantinatita.cl', max_length=254)),
                ('proximo_numero_boleta', models.PositiveIntegerField(default=1)),
                ('proximo_numero_factura', models.PositiveIntegerField(default=1)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('emite_boletas', models.BooleanField(default=True)),
                ('emite_facturas', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
            },
        ),
        migrations.CreateModel(
            name='HistorialFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_numero', models.CharField(max_length=20)),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('emitida', 'Emitida'), ('anulada', 'Anulada'), ('modificada', 'Modificada'), ('impresa', 'Impresa'), ('enviada', 'Enviada por Email')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Facturación',
                'verbose_name_plural': 'Historiales de Facturación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_rut', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
    ]
