# Generated by Django 5.2.7 on 2025-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_perfilestudiante_to_perfilhijo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilhijo',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Perfil de Hijo', 'verbose_name_plural': 'Perfiles de Hijos'},
        ),
        migrations.AlterField(
            model_name='perfilhijo',
            name='puede_saldo_negativo',
            field=models.BooleanField(default=False, help_text='Permite que el hijo tenga saldo negativo con autorización'),
        ),
    ]
