# Generated by Django 5.2.7 on 2025-10-11 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilhijo_options_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilhijo',
            name='codigo_tarjeta',
            field=models.CharField(blank=True, help_text='Código de seguridad de la tarjeta (para verificación en POS)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='perfilhijo',
            name='fecha_asignacion_tarjeta',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se asignó la tarjeta al hijo', null=True),
        ),
        migrations.AddField(
            model_name='perfilhijo',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Número único de la tarjeta exclusiva de La Cantina de Tita', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilhijo',
            name='tarjeta_activa',
            field=models.BooleanField(default=False, help_text='Indica si la tarjeta está activa para uso en puntos de venta'),
        ),
        migrations.CreateModel(
            name='TransaccionTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta_utilizada', models.CharField(help_text='Número de tarjeta utilizado en la transacción', max_length=16)),
                ('tipo_transaccion', models.CharField(choices=[('compra', 'Compra en POS'), ('recarga', 'Recarga de saldo'), ('ajuste', 'Ajuste manual'), ('devolucion', 'Devolución')], default='compra', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción (positivo para créditos, negativo para débitos)', max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, help_text='Saldo antes de la transacción', max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, help_text='Saldo después de la transacción', max_digits=10)),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('fallida', 'Fallida'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='exitosa', max_length=20)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('punto_venta', models.CharField(blank=True, help_text='Identificación del punto de venta donde se realizó', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_tarjeta', to='usuarios.perfilhijo')),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('venta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_tarjeta', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Transacción de Tarjeta',
                'verbose_name_plural': 'Transacciones de Tarjetas',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
