# Generated by Django 5.2.7 on 2025-10-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('consumo_estudiante', 'Consumo por Estudiante'), ('productos_mas_vendidos', 'Productos Más Vendidos'), ('ingresos_metodo_pago', 'Ingresos por Método de Pago'), ('ventas_diarias', 'Ventas Diarias'), ('stock_productos', 'Estado de Stock'), ('comisiones_pagos', 'Comisiones de Pagos')], max_length=30)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('hora_generacion', models.TimeField(help_text='Hora del día para generar el reporte automático')),
                ('activo', models.BooleanField(default=True)),
                ('destinatarios', models.TextField(help_text='Emails separados por comas para enviar el reporte')),
                ('fecha_ultimo_reporte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='DetalleReporteMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_transacciones', models.IntegerField()),
                ('comision_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Reporte por Método de Pago',
                'verbose_name_plural': 'Detalles de Reporte por Método de Pago',
                'ordering': ['-monto_total'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReporteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField()),
                ('monto_total_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_transacciones', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Reporte de Producto',
                'verbose_name_plural': 'Detalles de Reporte de Productos',
                'ordering': ['-cantidad_vendida'],
            },
        ),
        migrations.CreateModel(
            name='ReporteConsumoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('consumo_estudiante', 'Consumo por Estudiante'), ('productos_mas_vendidos', 'Productos Más Vendidos'), ('ingresos_metodo_pago', 'Ingresos por Método de Pago'), ('ventas_diarias', 'Ventas Diarias'), ('stock_productos', 'Estado de Stock'), ('comisiones_pagos', 'Comisiones de Pagos')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_transacciones', models.IntegerField(default=0)),
                ('producto_mas_comprado', models.CharField(blank=True, max_length=150)),
                ('promedio_gasto_diario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Reporte de Consumo de Estudiante',
                'verbose_name_plural': 'Reportes de Consumo de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='ReporteIngresosPorMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('consumo_estudiante', 'Consumo por Estudiante'), ('productos_mas_vendidos', 'Productos Más Vendidos'), ('ingresos_metodo_pago', 'Ingresos por Método de Pago'), ('ventas_diarias', 'Ventas Diarias'), ('stock_productos', 'Estado de Stock'), ('comisiones_pagos', 'Comisiones de Pagos')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Reporte de Ingresos por Método de Pago',
                'verbose_name_plural': 'Reportes de Ingresos por Método de Pago',
            },
        ),
        migrations.CreateModel(
            name='ReporteProductosMasVendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('consumo_estudiante', 'Consumo por Estudiante'), ('productos_mas_vendidos', 'Productos Más Vendidos'), ('ingresos_metodo_pago', 'Ingresos por Método de Pago'), ('ventas_diarias', 'Ventas Diarias'), ('stock_productos', 'Estado de Stock'), ('comisiones_pagos', 'Comisiones de Pagos')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
            ],
            options={
                'verbose_name': 'Reporte de Productos Más Vendidos',
                'verbose_name_plural': 'Reportes de Productos Más Vendidos',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_agotado', 'Stock Agotado'), ('stock_excesivo', 'Stock Excesivo')], max_length=15)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('notificada', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
