# Generated by Django 5.2.7 on 2025-10-14 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_initial'),
        ('reportes', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallereportemetodopago',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodopago'),
        ),
        migrations.AddField(
            model_name='detallereporteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='reporteconsumoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_consumo', to='usuarios.perfilhijo'),
        ),
        migrations.AddField(
            model_name='reporteconsumoestudiante',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_%(class)s_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteingresospormetodo',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_%(class)s_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallereportemetodopago',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_metodos', to='reportes.reporteingresospormetodo'),
        ),
        migrations.AddField(
            model_name='reporteproductosmasvendidos',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_%(class)s_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallereporteproducto',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='reportes.reporteproductosmasvendidos'),
        ),
    ]
